# Generated by Django 5.2.3 on 2025-09-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
