# Generated by Django 5.2.3 on 2025-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0002_rename_specialty_doctorprofile_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
