# Generated by Django 5.2.3 on 2026-04-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0005_alter_patientprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]

# Generated by Django 5.2.3 on 2026-03-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0005_alter_patientprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='additional_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
