# Generated by Django 5.2.3 on 2026-04-25 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0006_remove_patientprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedexercise',
            name='assigned_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
