# Generated by Django 5.2.3 on 2026-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0007_assignedexercise_assigned_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='additional_info',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
