# Generated by Django 5.2.3 on 2026-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0008_remove_doctorprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
